export const userRoutes = [
  {
    add: false,
    children: [
      {
        add: false,
        children: [],
        component: 'checkupManage/billManage/index',
        icon: 'envelope-open-text',
        id: 11,
        menuIsDeleted: 0,
        menuStatus: 1,
        meta: {
          icon: 'envelope-open-text',
          title: '体检办理',
        },
        name: 'Bill',
        order: 0,
        parentId: 10,
        path: '/bill',
        title: '体检办理',
      },
      {
        add: false,
        children: [],
        component: 'checkupManage/psManage/index',
        icon: 'bookmark',
        id: 12,
        menuIsDeleted: 0,
        menuStatus: 1,
        meta: {
          icon: 'bookmark',
          title: '体检小结',
        },
        name: 'Project_Summary',
        order: 0,
        parentId: 10,
        path: '/project_summary',
        title: '体检小结',
      },
      {
        add: false,
        children: [],
        component: 'checkupManage/csManage/index',
        icon: 'book-medical',
        id: 13,
        menuIsDeleted: 0,
        menuStatus: 1,
        meta: {
          icon: 'book-medical',
          title: '体检总结',
        },
        name: 'CheckUp_Summary',
        order: 0,
        parentId: 10,
        path: '/checkup_summary',
        title: '体检总结',
      },
    ],
    component: 'Layout',
    icon: 'check-square',
    id: 10,
    menuIsDeleted: 0,
    menuStatus: 1,
    meta: {
      icon: 'check-square',
      title: '体检工作',
    },
    name: 'CheckUp',
    order: 0,
    parentId: 0,
    path: '/checkup',
    redirect: 'noRedirect',
    title: '体检工作',
  },
]
